FROM maven:3.6.2-jdk-11 as builder

WORKDIR /build
RUN git clone --branch support-4.2 --single-branch https://github.com/Evolveum/midpoint \
  && cd midpoint

WORKDIR /build/midpoint
RUN mvn dependency:resolve

ARG REVISION=640218dd3d3a61c565dd5b2470e02a14fd0d403e
RUN git checkout $REVISION

RUN mvn package -DskipTests=true -Dmaven.javadoc.skip=true
RUN mv gui/admin-gui/target/midpoint-executable.war /build/midpoint.war \
  && git rev-parse HEAD > /build/VERSION.txt


FROM alpine:3.11.6

ENV JAVA_HOME /usr/lib/jvm/default-jvm
ENV PATH $PATH:$JAVA_HOME/bin
RUN apk update \
  && apk --no-cache add openjdk11-jdk tzdata \
  && rm -rf /var/cache/apk/*

ENV MP_DIR /opt/midpoint
RUN mkdir -p ${MP_DIR}/var && mkdir -p ${MP_DIR}/lib

COPY --from=builder /build/midpoint.war ${MP_DIR}/lib/
COPY --from=builder /build/VERSION.txt ${MP_DIR}/

EXPOSE 8080

