name: Build and push docker image on support-4.1

on: 
   push:
     tags:
       - 'v4.1-*'
env:
  DOCKER_FILE: Dockerfile-4.1

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check tag 
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "TAG=$TAG"
          REVISION=`grep "^ARG REVISION=" $DOCKER_FILE | cut -d "=" -f 2`
          echo "REVISION=$REVISION"
          if [ "$TAG" != "v4.1-$REVISION" ]; then
            echo "Detect revision mismatch!! "
            exit 1
          fi

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :tag
        if: success()
        run: docker build -f $DOCKER_FILE -t openstandia/midpoint:${IMAGE_TAG} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push openstandia/midpoint:${IMAGE_TAG}
